# Query Strings may be composed of
# a sequence of (multiple) filters/handlers

# Psuedo Syntax:
# shorthand | handler filter | filter handler 

# When args[].length == 0
Default_Query: http://userbound.com

Handlers:
  # Non-URI Based handlers
  default   : surf
  surf      : surf %s
  chr       : chromium %s
  private   : chromium --incognito %s
  ff        : firefox %s

  # Termial Handlers
  sh        : urxvt -e %s
  yt        : urxvt -e youtube-viewer %s
  j         : urxvt -cd (j %s) -e ranger
  ranger    : urxvt -cd %s -e ranger
  kill      : killall %s
  man       : urxvt -e man %s
  cd        : ranger %s
  workspace : fish -c "workspace %s"

Searches:
  default  : gg

  # Searches Queries
  ddg      : https://duckduckgo.com/?q=%s
  gg       : https://google.com/search?q=%s
  im       : https://google.com/search?tbm=isch&q=%s
  maps     : https://maps.google.com/maps?q=%s

  wiki     : https://en.wikipedia.org/w/index.php?search=%s
  wb       : https://secure.wikimedia.org/wikibooks/en/wiki?search=%s
  aur      : https://aur.archlinux.org/packages.php?O=0&K=%s&do_Search=Go
  aw       : https://wiki.archlinux.org/index.php?search=%s
  so       : https://stackoverflow.com/search?q=%s
  gh       : https://github.com/search?q=%s
  wa       : https://wolframalpha.com/input?i=%s
  discogs  : https://discogs.com/search?q=%s
  rym      : https://rateyourmusic.com/search?searchterm=%s&searchtype=a
  sep      : https://plato.stanford.edu/search/searcher.py?query=%s
  ud       : https://urbandictionary.com/define.php?term=%s
  ebay     : https://search.ebay.com/search/search.dll?query=%s
  stock    : https://www.google.com/finance?q=%s
  define   : http://www.merriam-webster.com/dictionary/%s
  syn      : http://www.collinsdictionary.com/dictionary/english-thesaurus/%s
  weather  : http://asciiw.com/?%s


Shorthands:
  config    : urxvt -e vim /home/mil/.lunchcfg.yaml

  # Hosts
  site5     : urxvt -e ssh miles@userbound.com
  dreamhost : urxvt -e ssh bladdo@bladdo.net
  x300      : urxvt -e ssh mil@x300
  x40       : urxvt -e ssh mil@x40
  sys13     : urxvt -e ssh mil@sys13

  # Apps
  chromium  : chromium
  firefox   : firefox

  # Location / Convienent
  email    : urxvt -e mutt
  campus   : campus
  home     : home
  wuvt     : urxvt -fn "xft:Envy Code R-30" -e sleepit 10 wuvt
  bt       : urxvt -fn "xft:Envy Code R-30" -e sleepit 10 bt

  # Alarm Clock
  wakeup  : wakeup
  cron    : urxvt -e crontab -e

  # Tmux Sessions
  notes   : urxvt -e tmx notes
  music   : urxvt -e dtach -A /home/mil/IPC/Sockets/music fish -c dvtm
  torrent : urxvt -e dtach -A /home/mil/IPC/Sockets/torrent fish -c dvtm
  irc     : urxvt -e dtach -A /home/mil/IPC/Sockets/irc fish -c dvtm
  chat    : urxvt -e dtach -A /home/mil/IPC/Sockets/chat fish -c pidgin
  network : urxvt -e tmx network
  system  : urxvt -e tmx system

  # Audio
  mute     : amixer set Master 0% mute
  mixer    : urxvt -e alsamixer
  eq       : urxvt -e alsamixer -D equal
  pause    : mediaControl pause
  next     : mediaControl next
  previous : mediaControl previous
  dj       : urxvt -e mpctrl

  # Displays
  mntrs      : arandr
  viewsonic  : viewsonic
  lcd        : lcd
  dualscreen : dualscreen
  goodnight  : xset dpms force suspend
  lock       : slock
  invert     : xcalib -a -invert

  # Design
  calibrate  : urxvt -e dispwin
  gimp       : gimp
  phatch     : phatch
  picker     : gcolor2
  ruler      : xmeasure | tr -d '\n' | xargs -I INF zenity --info --text='INF'
  screenshot : scrot

  # Skanote
  skanote-dev : chromium --app=http://localhost:9292
  skanote     : chromium --app=http://morning-plains-8512.herokuapp.com'

  # Misc System
  root      : urxvt -e sudo su
  remap     : xmodmap ~/.xmodmap
  fans      : fans
  suspend   : sudo pm-suspend
  shutdown  : sudo /usr/bin/systemctl hibernate
  reboot    : sudo /usr/bin/systemctl reboot
  halt      : sudo /usr/bin/systemctl poweroff


  # Games
  clock   : urxvt -fn "xft:Envy Code R-20" -e tty-clock -c -s -C 2
  tetris  : urxvt -e vitetris
  word    : abiword

  # Tools

  # Bookmarks
  bookmarks : urxvt -e ranger /home/mil/Code/Bitbucket/bookmarks
  otw       : http://onethingwell.org
  hn        : http://news.ycombinator.com
  gh        : http://geekhack.org
  bb        : http://bitbucket.org
  bb        : http://bitbucket.org
  scholar   : http://scholar.vt.edu
  lib       : surf 'https://login.ezproxy.lib.vt.edu:2443/login?qurl=http%3A//www.lib.vt.edu/'
